// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXaGW_mHYuoAJRKBqsA26WFPh9rNV33k',
    appId: '1:358494008737:android:4790598aef9137203fc7e0',
    messagingSenderId: '358494008737',
    projectId: 'snapmap-f4706',
    databaseURL: 'https://snapmap-f4706-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'snapmap-f4706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbrZpZI6zKykBYpXTw-aQz_7AWknQbJE4',
    appId: '1:358494008737:ios:2ecef5d360128f453fc7e0',
    messagingSenderId: '358494008737',
    projectId: 'snapmap-f4706',
    databaseURL: 'https://snapmap-f4706-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'snapmap-f4706.firebasestorage.app',
    iosBundleId: 'com.baskent.snapmap',
  );
}